name = "memory"
description = "Safety functions used in place of Rust within the mm crate"
version = "0.1.0-dev"

authors = ["Alessio Maroni"]
maintainers = ["Alessio Maroni <alessioMaroni0@gmail.com>"]
maintainers-logins = ["alessioMaroni"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
